name: Build CSV Downloader Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS app
        run: |
          pyinstaller --onefile --windowed --name "CSV Downloader" csv_downloader.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSV-Downloader-macOS
          path: dist/CSV\ Downloader

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows exe
        run: |
          pyinstaller --onefile --windowed --name "CSV Downloader" csv_downloader.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSV-Downloader-Windows
          path: dist/CSV Downloader.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux binary
        run: |
          pyinstaller --onefile --windowed --name "CSV Downloader" csv_downloader.py

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSV-Downloader-Linux
          path: dist/CSV\ Downloader
